//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISSoap")]
    public interface ISSoap {
        
        // CODEGEN: Generating message contract since element name NameMachine from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receiveMachines", ReplyAction="*")]
        WS.ServiceReference1.receiveMachinesResponse receiveMachines(WS.ServiceReference1.receiveMachinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receiveMachines", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.receiveMachinesResponse> receiveMachinesAsync(WS.ServiceReference1.receiveMachinesRequest request);
        
        // CODEGEN: Generating message contract since element name PC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeStatusMachinesFALSE", ReplyAction="*")]
        WS.ServiceReference1.changeStatusMachinesFALSEResponse changeStatusMachinesFALSE(WS.ServiceReference1.changeStatusMachinesFALSERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeStatusMachinesFALSE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesFALSEResponse> changeStatusMachinesFALSEAsync(WS.ServiceReference1.changeStatusMachinesFALSERequest request);
        
        // CODEGEN: Generating message contract since element name PC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStatusMachinesFALSE", ReplyAction="*")]
        WS.ServiceReference1.searchStatusMachinesFALSEResponse searchStatusMachinesFALSE(WS.ServiceReference1.searchStatusMachinesFALSERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStatusMachinesFALSE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesFALSEResponse> searchStatusMachinesFALSEAsync(WS.ServiceReference1.searchStatusMachinesFALSERequest request);
        
        // CODEGEN: Generating message contract since element name PC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeStatusMachinesTRUE", ReplyAction="*")]
        WS.ServiceReference1.changeStatusMachinesTRUEResponse changeStatusMachinesTRUE(WS.ServiceReference1.changeStatusMachinesTRUERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeStatusMachinesTRUE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesTRUEResponse> changeStatusMachinesTRUEAsync(WS.ServiceReference1.changeStatusMachinesTRUERequest request);
        
        // CODEGEN: Generating message contract since element name PC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStatusMachinesTRUE", ReplyAction="*")]
        WS.ServiceReference1.searchStatusMachinesTRUEResponse searchStatusMachinesTRUE(WS.ServiceReference1.searchStatusMachinesTRUERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStatusMachinesTRUE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesTRUEResponse> searchStatusMachinesTRUEAsync(WS.ServiceReference1.searchStatusMachinesTRUERequest request);
        
        // CODEGEN: Generating message contract since element name nameMachine from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMachinesTRUE", ReplyAction="*")]
        WS.ServiceReference1.searchMachinesTRUEResponse searchMachinesTRUE(WS.ServiceReference1.searchMachinesTRUERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMachinesTRUE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesTRUEResponse> searchMachinesTRUEAsync(WS.ServiceReference1.searchMachinesTRUERequest request);
        
        // CODEGEN: Generating message contract since element name nameMachine from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMachinesFALSE", ReplyAction="*")]
        WS.ServiceReference1.searchMachinesFALSEResponse searchMachinesFALSE(WS.ServiceReference1.searchMachinesFALSERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMachinesFALSE", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesFALSEResponse> searchMachinesFALSEAsync(WS.ServiceReference1.searchMachinesFALSERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/showmachinesFALSE", ReplyAction="*")]
        void showmachinesFALSE();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/showmachinesFALSE", ReplyAction="*")]
        System.Threading.Tasks.Task showmachinesFALSEAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMachinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMachines", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.receiveMachinesRequestBody Body;
        
        public receiveMachinesRequest() {
        }
        
        public receiveMachinesRequest(WS.ServiceReference1.receiveMachinesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class receiveMachinesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameMachine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool connection;
        
        public receiveMachinesRequestBody() {
        }
        
        public receiveMachinesRequestBody(string NameMachine, bool connection) {
            this.NameMachine = NameMachine;
            this.connection = connection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMachinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMachinesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.receiveMachinesResponseBody Body;
        
        public receiveMachinesResponse() {
        }
        
        public receiveMachinesResponse(WS.ServiceReference1.receiveMachinesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class receiveMachinesResponseBody {
        
        public receiveMachinesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeStatusMachinesFALSERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeStatusMachinesFALSE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.changeStatusMachinesFALSERequestBody Body;
        
        public changeStatusMachinesFALSERequest() {
        }
        
        public changeStatusMachinesFALSERequest(WS.ServiceReference1.changeStatusMachinesFALSERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changeStatusMachinesFALSERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public changeStatusMachinesFALSERequestBody() {
        }
        
        public changeStatusMachinesFALSERequestBody(string PC, bool status) {
            this.PC = PC;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeStatusMachinesFALSEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeStatusMachinesFALSEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.changeStatusMachinesFALSEResponseBody Body;
        
        public changeStatusMachinesFALSEResponse() {
        }
        
        public changeStatusMachinesFALSEResponse(WS.ServiceReference1.changeStatusMachinesFALSEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changeStatusMachinesFALSEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool changeStatusMachinesFALSEResult;
        
        public changeStatusMachinesFALSEResponseBody() {
        }
        
        public changeStatusMachinesFALSEResponseBody(bool changeStatusMachinesFALSEResult) {
            this.changeStatusMachinesFALSEResult = changeStatusMachinesFALSEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchStatusMachinesFALSERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchStatusMachinesFALSE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchStatusMachinesFALSERequestBody Body;
        
        public searchStatusMachinesFALSERequest() {
        }
        
        public searchStatusMachinesFALSERequest(WS.ServiceReference1.searchStatusMachinesFALSERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchStatusMachinesFALSERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public searchStatusMachinesFALSERequestBody() {
        }
        
        public searchStatusMachinesFALSERequestBody(string PC, bool status) {
            this.PC = PC;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchStatusMachinesFALSEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchStatusMachinesFALSEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchStatusMachinesFALSEResponseBody Body;
        
        public searchStatusMachinesFALSEResponse() {
        }
        
        public searchStatusMachinesFALSEResponse(WS.ServiceReference1.searchStatusMachinesFALSEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchStatusMachinesFALSEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool searchStatusMachinesFALSEResult;
        
        public searchStatusMachinesFALSEResponseBody() {
        }
        
        public searchStatusMachinesFALSEResponseBody(bool searchStatusMachinesFALSEResult) {
            this.searchStatusMachinesFALSEResult = searchStatusMachinesFALSEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeStatusMachinesTRUERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeStatusMachinesTRUE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.changeStatusMachinesTRUERequestBody Body;
        
        public changeStatusMachinesTRUERequest() {
        }
        
        public changeStatusMachinesTRUERequest(WS.ServiceReference1.changeStatusMachinesTRUERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changeStatusMachinesTRUERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public changeStatusMachinesTRUERequestBody() {
        }
        
        public changeStatusMachinesTRUERequestBody(string PC, bool status) {
            this.PC = PC;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeStatusMachinesTRUEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeStatusMachinesTRUEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.changeStatusMachinesTRUEResponseBody Body;
        
        public changeStatusMachinesTRUEResponse() {
        }
        
        public changeStatusMachinesTRUEResponse(WS.ServiceReference1.changeStatusMachinesTRUEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changeStatusMachinesTRUEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool changeStatusMachinesTRUEResult;
        
        public changeStatusMachinesTRUEResponseBody() {
        }
        
        public changeStatusMachinesTRUEResponseBody(bool changeStatusMachinesTRUEResult) {
            this.changeStatusMachinesTRUEResult = changeStatusMachinesTRUEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchStatusMachinesTRUERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchStatusMachinesTRUE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchStatusMachinesTRUERequestBody Body;
        
        public searchStatusMachinesTRUERequest() {
        }
        
        public searchStatusMachinesTRUERequest(WS.ServiceReference1.searchStatusMachinesTRUERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchStatusMachinesTRUERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public searchStatusMachinesTRUERequestBody() {
        }
        
        public searchStatusMachinesTRUERequestBody(string PC, bool status) {
            this.PC = PC;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchStatusMachinesTRUEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchStatusMachinesTRUEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchStatusMachinesTRUEResponseBody Body;
        
        public searchStatusMachinesTRUEResponse() {
        }
        
        public searchStatusMachinesTRUEResponse(WS.ServiceReference1.searchStatusMachinesTRUEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchStatusMachinesTRUEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool searchStatusMachinesTRUEResult;
        
        public searchStatusMachinesTRUEResponseBody() {
        }
        
        public searchStatusMachinesTRUEResponseBody(bool searchStatusMachinesTRUEResult) {
            this.searchStatusMachinesTRUEResult = searchStatusMachinesTRUEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchMachinesTRUERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchMachinesTRUE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchMachinesTRUERequestBody Body;
        
        public searchMachinesTRUERequest() {
        }
        
        public searchMachinesTRUERequest(WS.ServiceReference1.searchMachinesTRUERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchMachinesTRUERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameMachine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public searchMachinesTRUERequestBody() {
        }
        
        public searchMachinesTRUERequestBody(string nameMachine, bool status) {
            this.nameMachine = nameMachine;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchMachinesTRUEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchMachinesTRUEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchMachinesTRUEResponseBody Body;
        
        public searchMachinesTRUEResponse() {
        }
        
        public searchMachinesTRUEResponse(WS.ServiceReference1.searchMachinesTRUEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchMachinesTRUEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool searchMachinesTRUEResult;
        
        public searchMachinesTRUEResponseBody() {
        }
        
        public searchMachinesTRUEResponseBody(bool searchMachinesTRUEResult) {
            this.searchMachinesTRUEResult = searchMachinesTRUEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchMachinesFALSERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchMachinesFALSE", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchMachinesFALSERequestBody Body;
        
        public searchMachinesFALSERequest() {
        }
        
        public searchMachinesFALSERequest(WS.ServiceReference1.searchMachinesFALSERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchMachinesFALSERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameMachine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public searchMachinesFALSERequestBody() {
        }
        
        public searchMachinesFALSERequestBody(string nameMachine, bool status) {
            this.nameMachine = nameMachine;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchMachinesFALSEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchMachinesFALSEResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS.ServiceReference1.searchMachinesFALSEResponseBody Body;
        
        public searchMachinesFALSEResponse() {
        }
        
        public searchMachinesFALSEResponse(WS.ServiceReference1.searchMachinesFALSEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchMachinesFALSEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool searchMachinesFALSEResult;
        
        public searchMachinesFALSEResponseBody() {
        }
        
        public searchMachinesFALSEResponseBody(bool searchMachinesFALSEResult) {
            this.searchMachinesFALSEResult = searchMachinesFALSEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISSoapChannel : WS.ServiceReference1.ISSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSoapClient : System.ServiceModel.ClientBase<WS.ServiceReference1.ISSoap>, WS.ServiceReference1.ISSoap {
        
        public SSoapClient() {
        }
        
        public SSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.receiveMachinesResponse WS.ServiceReference1.ISSoap.receiveMachines(WS.ServiceReference1.receiveMachinesRequest request) {
            return base.Channel.receiveMachines(request);
        }
        
        public void receiveMachines(string NameMachine, bool connection) {
            WS.ServiceReference1.receiveMachinesRequest inValue = new WS.ServiceReference1.receiveMachinesRequest();
            inValue.Body = new WS.ServiceReference1.receiveMachinesRequestBody();
            inValue.Body.NameMachine = NameMachine;
            inValue.Body.connection = connection;
            WS.ServiceReference1.receiveMachinesResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).receiveMachines(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.receiveMachinesResponse> WS.ServiceReference1.ISSoap.receiveMachinesAsync(WS.ServiceReference1.receiveMachinesRequest request) {
            return base.Channel.receiveMachinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.receiveMachinesResponse> receiveMachinesAsync(string NameMachine, bool connection) {
            WS.ServiceReference1.receiveMachinesRequest inValue = new WS.ServiceReference1.receiveMachinesRequest();
            inValue.Body = new WS.ServiceReference1.receiveMachinesRequestBody();
            inValue.Body.NameMachine = NameMachine;
            inValue.Body.connection = connection;
            return ((WS.ServiceReference1.ISSoap)(this)).receiveMachinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.changeStatusMachinesFALSEResponse WS.ServiceReference1.ISSoap.changeStatusMachinesFALSE(WS.ServiceReference1.changeStatusMachinesFALSERequest request) {
            return base.Channel.changeStatusMachinesFALSE(request);
        }
        
        public bool changeStatusMachinesFALSE(string PC, bool status) {
            WS.ServiceReference1.changeStatusMachinesFALSERequest inValue = new WS.ServiceReference1.changeStatusMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.changeStatusMachinesFALSERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            WS.ServiceReference1.changeStatusMachinesFALSEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).changeStatusMachinesFALSE(inValue);
            return retVal.Body.changeStatusMachinesFALSEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesFALSEResponse> WS.ServiceReference1.ISSoap.changeStatusMachinesFALSEAsync(WS.ServiceReference1.changeStatusMachinesFALSERequest request) {
            return base.Channel.changeStatusMachinesFALSEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesFALSEResponse> changeStatusMachinesFALSEAsync(string PC, bool status) {
            WS.ServiceReference1.changeStatusMachinesFALSERequest inValue = new WS.ServiceReference1.changeStatusMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.changeStatusMachinesFALSERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).changeStatusMachinesFALSEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.searchStatusMachinesFALSEResponse WS.ServiceReference1.ISSoap.searchStatusMachinesFALSE(WS.ServiceReference1.searchStatusMachinesFALSERequest request) {
            return base.Channel.searchStatusMachinesFALSE(request);
        }
        
        public bool searchStatusMachinesFALSE(string PC, bool status) {
            WS.ServiceReference1.searchStatusMachinesFALSERequest inValue = new WS.ServiceReference1.searchStatusMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.searchStatusMachinesFALSERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            WS.ServiceReference1.searchStatusMachinesFALSEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).searchStatusMachinesFALSE(inValue);
            return retVal.Body.searchStatusMachinesFALSEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesFALSEResponse> WS.ServiceReference1.ISSoap.searchStatusMachinesFALSEAsync(WS.ServiceReference1.searchStatusMachinesFALSERequest request) {
            return base.Channel.searchStatusMachinesFALSEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesFALSEResponse> searchStatusMachinesFALSEAsync(string PC, bool status) {
            WS.ServiceReference1.searchStatusMachinesFALSERequest inValue = new WS.ServiceReference1.searchStatusMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.searchStatusMachinesFALSERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).searchStatusMachinesFALSEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.changeStatusMachinesTRUEResponse WS.ServiceReference1.ISSoap.changeStatusMachinesTRUE(WS.ServiceReference1.changeStatusMachinesTRUERequest request) {
            return base.Channel.changeStatusMachinesTRUE(request);
        }
        
        public bool changeStatusMachinesTRUE(string PC, bool status) {
            WS.ServiceReference1.changeStatusMachinesTRUERequest inValue = new WS.ServiceReference1.changeStatusMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.changeStatusMachinesTRUERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            WS.ServiceReference1.changeStatusMachinesTRUEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).changeStatusMachinesTRUE(inValue);
            return retVal.Body.changeStatusMachinesTRUEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesTRUEResponse> WS.ServiceReference1.ISSoap.changeStatusMachinesTRUEAsync(WS.ServiceReference1.changeStatusMachinesTRUERequest request) {
            return base.Channel.changeStatusMachinesTRUEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.changeStatusMachinesTRUEResponse> changeStatusMachinesTRUEAsync(string PC, bool status) {
            WS.ServiceReference1.changeStatusMachinesTRUERequest inValue = new WS.ServiceReference1.changeStatusMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.changeStatusMachinesTRUERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).changeStatusMachinesTRUEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.searchStatusMachinesTRUEResponse WS.ServiceReference1.ISSoap.searchStatusMachinesTRUE(WS.ServiceReference1.searchStatusMachinesTRUERequest request) {
            return base.Channel.searchStatusMachinesTRUE(request);
        }
        
        public bool searchStatusMachinesTRUE(string PC, bool status) {
            WS.ServiceReference1.searchStatusMachinesTRUERequest inValue = new WS.ServiceReference1.searchStatusMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.searchStatusMachinesTRUERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            WS.ServiceReference1.searchStatusMachinesTRUEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).searchStatusMachinesTRUE(inValue);
            return retVal.Body.searchStatusMachinesTRUEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesTRUEResponse> WS.ServiceReference1.ISSoap.searchStatusMachinesTRUEAsync(WS.ServiceReference1.searchStatusMachinesTRUERequest request) {
            return base.Channel.searchStatusMachinesTRUEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.searchStatusMachinesTRUEResponse> searchStatusMachinesTRUEAsync(string PC, bool status) {
            WS.ServiceReference1.searchStatusMachinesTRUERequest inValue = new WS.ServiceReference1.searchStatusMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.searchStatusMachinesTRUERequestBody();
            inValue.Body.PC = PC;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).searchStatusMachinesTRUEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.searchMachinesTRUEResponse WS.ServiceReference1.ISSoap.searchMachinesTRUE(WS.ServiceReference1.searchMachinesTRUERequest request) {
            return base.Channel.searchMachinesTRUE(request);
        }
        
        public bool searchMachinesTRUE(string nameMachine, bool status) {
            WS.ServiceReference1.searchMachinesTRUERequest inValue = new WS.ServiceReference1.searchMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.searchMachinesTRUERequestBody();
            inValue.Body.nameMachine = nameMachine;
            inValue.Body.status = status;
            WS.ServiceReference1.searchMachinesTRUEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).searchMachinesTRUE(inValue);
            return retVal.Body.searchMachinesTRUEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesTRUEResponse> WS.ServiceReference1.ISSoap.searchMachinesTRUEAsync(WS.ServiceReference1.searchMachinesTRUERequest request) {
            return base.Channel.searchMachinesTRUEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesTRUEResponse> searchMachinesTRUEAsync(string nameMachine, bool status) {
            WS.ServiceReference1.searchMachinesTRUERequest inValue = new WS.ServiceReference1.searchMachinesTRUERequest();
            inValue.Body = new WS.ServiceReference1.searchMachinesTRUERequestBody();
            inValue.Body.nameMachine = nameMachine;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).searchMachinesTRUEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.ServiceReference1.searchMachinesFALSEResponse WS.ServiceReference1.ISSoap.searchMachinesFALSE(WS.ServiceReference1.searchMachinesFALSERequest request) {
            return base.Channel.searchMachinesFALSE(request);
        }
        
        public bool searchMachinesFALSE(string nameMachine, bool status) {
            WS.ServiceReference1.searchMachinesFALSERequest inValue = new WS.ServiceReference1.searchMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.searchMachinesFALSERequestBody();
            inValue.Body.nameMachine = nameMachine;
            inValue.Body.status = status;
            WS.ServiceReference1.searchMachinesFALSEResponse retVal = ((WS.ServiceReference1.ISSoap)(this)).searchMachinesFALSE(inValue);
            return retVal.Body.searchMachinesFALSEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesFALSEResponse> WS.ServiceReference1.ISSoap.searchMachinesFALSEAsync(WS.ServiceReference1.searchMachinesFALSERequest request) {
            return base.Channel.searchMachinesFALSEAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.ServiceReference1.searchMachinesFALSEResponse> searchMachinesFALSEAsync(string nameMachine, bool status) {
            WS.ServiceReference1.searchMachinesFALSERequest inValue = new WS.ServiceReference1.searchMachinesFALSERequest();
            inValue.Body = new WS.ServiceReference1.searchMachinesFALSERequestBody();
            inValue.Body.nameMachine = nameMachine;
            inValue.Body.status = status;
            return ((WS.ServiceReference1.ISSoap)(this)).searchMachinesFALSEAsync(inValue);
        }
        
        public void showmachinesFALSE() {
            base.Channel.showmachinesFALSE();
        }
        
        public System.Threading.Tasks.Task showmachinesFALSEAsync() {
            return base.Channel.showmachinesFALSEAsync();
        }
    }
}
